### ISSUE TITLE
Update a URL in the documentation

### ISSUE THREAD

**Issue by zrmor** [nipreps/.github#6]
### What would you like changed/added and why?

In [this page ](https://www.nipreps.org/apps/framework/) and under the 'What are BIDS Derivatives?' section, the url to '**draft**' has changed from [this page](https://bids-specification.readthedocs.io/en/derivatives/) which doesn't exist any more to[ this page](https://bids-specification.readthedocs.io/en/stable/derivatives/introduction.html), I suppose.

### Do you have any interest in helping improve the documentation?

Yes

**Comment by effigies** [comment]
I agree. The repository to fix this in is https://github.com/nipreps/nipreps.github.io.

**Comment by zrmor** [comment]
I updated the url and created [a pull request](https://github.com/nipreps/nipreps.github.io/pull/33) accordingly.
